### ISSUE TITLE
Theory behind automatic rotation Euler angles 

### ISSUE THREAD

**Issue by WalterWhite1611** [Chengcheng-Xiao/RotSph#2]
I just applied your code on my material to get accurate projection coefficients for $d$ orbitals along unit cell z direction. After performing LORBIT=12 calculation, I found best possible Euler's angles for $d$ orbitals. Now I was just wondering what is the theory and algorithm behind `find_angle.py` script and how it's related to those phase of orbitals,which I extracted from LORBIT=12 ? Thank you for this great code.

**Comment by Chengcheng-Xiao** [comment]
Hi @WalterWhite1611, if I'm not mistaken, you asked the [question on stack exchange](https://mattermodeling.stackexchange.com/questions/12838/d-orbitals-pdos-analysis) so I'm back linking it here.

It would be nice to know if this code works and have your updated plot here ;)

> Now I was just wondering what is the theory and algorithm behind the `find_angle.py` script and how it's related to those phases of orbitals, which I extracted from LORBIT=12?

At the moment, the best Eulrr angles are found by performing an exhaust search that gives the largest coefficients. If you want more details, I'm in the process of integrating this into Pymatgen and will be writing up a short paper on how and the performance of this algorithm.

Also, I would really appreciate it if you can cite this repo using the following temporary BibTeX entry in any publication that uses it:
```
@software{rotsph,
   author = {Chengcheng Xiao},
   title = {rotsph: a code to calculate the rotation matrix of real spherical harmonics},
   url = {https://github.com/Chengcheng-Xiao/RotSph},
   year = {2024}
}
```

**Comment by Chengcheng-Xiao** [comment]
Closed due to inactivity.
