### ISSUE TITLE
QE support?

### ISSUE THREAD

**Issue by AbdulMuhaymin** [Chengcheng-Xiao/RotSph#3]
Hi! 
I am wondering if you are planning to add Quantum ESPRESSO support to this. I don't understand the algorithm/theory but I think your code can do what I am looking for. Correct me if I am wrong. 

For an isolated Cu atom, after a `pw.x`, and a subsequent `projwfc.x` run with [`diag_basis = .false.`](https://www.quantum-espresso.org/Doc/INPUT_PROJWFC.html#idm37), I have correctly obtained 5 degenerate 3d levels. However, I'd expect each degenerate level is coming due to sole contribution of a single state. However, I have found something like:
```
...
     state #   6: atom   1 (Cu ), wfc  4 (l=2 m= 1)
     state #   7: atom   1 (Cu ), wfc  4 (l=2 m= 2)
     state #   8: atom   1 (Cu ), wfc  4 (l=2 m= 3)
     state #   9: atom   1 (Cu ), wfc  4 (l=2 m= 4)
     state #  10: atom   1 (Cu ), wfc  4 (l=2 m= 5)
...
==== e(   5) =    -5.03793 eV ==== 
     psi = 0.337*[#   6]+0.337*[#   9]+0.108*[#   7]+0.108*[#   8]+0.108*[#  10]
    |psi|^2 = 1.000
==== e(   6) =    -5.03793 eV ==== 
     psi = 0.250*[#   7]+0.250*[#   8]+0.250*[#  10]+0.125*[#   6]+0.125*[#   9]
    |psi|^2 = 1.000
==== e(   7) =    -5.03793 eV ==== 
     psi = 0.210*[#   6]+0.210*[#   9]+0.193*[#   7]+0.193*[#   8]+0.193*[#  10]
    |psi|^2 = 1.000
==== e(   8) =    -5.03793 eV ==== 
     psi = 0.320*[#   6]+0.320*[#   9]+0.120*[#   7]+0.120*[#   8]+0.120*[#  10]
    |psi|^2 = 1.000
==== e(   9) =    -5.03793 eV ==== 
     psi = 0.329*[#   7]+0.329*[#   8]+0.329*[#  10]+0.007*[#   6]+0.007*[#   9]
    |psi|^2 = 1.000
...
```
Even after using `diag_basis=.true.`, I didn't get the expected outcome. 
```
...
     state #   6: atom   1 (Cu ), wfc  4 (l=2 m= 1)
     state #   7: atom   1 (Cu ), wfc  4 (l=2 m= 2)
     state #   8: atom   1 (Cu ), wfc  4 (l=2 m= 3)
     state #   9: atom   1 (Cu ), wfc  4 (l=2 m= 4)
     state #  10: atom   1 (Cu ), wfc  4 (l=2 m= 5)
...
==== e(   5) =    -5.03795 eV ==== 
     psi = 0.499*[#   6]+0.499*[#   9]
    |psi|^2 = 1.000
==== e(   6) =    -5.03795 eV ==== 
     psi = 0.499*[#   6]+0.499*[#   9]
    |psi|^2 = 1.000
==== e(   7) =    -5.03795 eV ==== 
     psi = 0.333*[#   7]+0.333*[#   8]+0.333*[#  10]
    |psi|^2 = 1.000
==== e(   8) =    -5.03795 eV ==== 
     psi = 0.333*[#   7]+0.333*[#   8]+0.333*[#  10]+0.001*[#   6]+0.001*[#   9]
    |psi|^2 = 1.000
==== e(   9) =    -5.03795 eV ==== 
     psi = 0.333*[#   7]+0.333*[#   8]+0.333*[#  10]
    |psi|^2 = 1.000
...
```

I understand that this could be due to rotated orbital issue. Is it possible with your code to fix this?

**Comment by Chengcheng-Xiao** [comment]
> I am wondering if you are planning to add Quantum ESPRESSO support to this. 

I do plan to add this to [pymatgen](https://pymatgen.org) in the future. However, porting it to QE might be a bit harder since the phase factors are not printed out by `projwfc.x`. Some hacking might be required.

> Is it possible with your code to fix this? 

This sounds like a situation where RotSph can help. Alternatively, you can rotate your box and check if that helps. e.g.,
```
[[1,0,0],[0,1,0][0,0,1]] -> [[1/sqrt{2},1/sqrt{2},0],[-1/sqrt{2},1/sqrt{2},0],[0,0,1]]
```

 However, I don't believe there's anything to fix for an isolated atom as in theory, these orbitals should be rotationally invariant. You are seeing an eg-t2g-like contribution because you are using a cubic box and the periodic images induce a crystal field that has a similar effect as a octahedral field.

**Comment by AbdulMuhaymin** [comment]
Thank you for the response.
> However, porting it to QE might be a bit harder since the phase factors are not printed out by projwfc.x

Maybe we can extract this information from the `.hdf5` wavefunction files

> However, I don't believe there's anything to fix for an isolated atom as in theory, these orbitals should be rotationally invariant. You are seeing an eg-t2g-like contribution because you are using a cubic box and the periodic images induce a crystal field that has a similar effect as a octahedral field.

I have added a very large vacuum (30 Ang) which should effectively cancel any eg-t2g contribution. 

In any case, thank you. I have tried atomic-basis like code (SIESTA) and they correctly gave the 5-fold degeneracy with correct orbital projection with only 15 Ang vacuum.

**Comment by Chengcheng-Xiao** [comment]
> Maybe we can extract this information from the `.hdf5` wavefunction files

The wavefunction files can for sure be used to generate desired coeffs, but one would need to divise a projection routine which feels like reinventing the wheel at the moment ;) Maybe I'll give it a whirl at some time in the future.

> In any case, thank you. I have tried atomic-basis like code (SIESTA) and they correctly gave the 5-fold degeneracy with correct orbital projection with only 15 Ang vacuum.

Glad it you got it worked out! Closing this issue for now.
